[build]
  # first installs root deps, then builds your React app
  command   = "npm install && npm run build-client"
  publish   = "rental-platform-frontend/build"

[functions]
  # where our single api.js lives
  directory = "netlify/functions"

# any /admin/* → function at /.netlify/functions/api/admin/...
[[redirects]]
  from    = "/admin/*"
  to      = "/.netlify/functions/api/admin/:splat"
  status  = 200
  force   = true

# any /api/* → function at /.netlify/functions/api/api/...
[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/api/api/:splat"
  status  = 200
  force   = true

# push everything else into your SPA:
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
