[build]
  base    = "rental-platform-frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  # this is where your single api.js “wrapper” lives
  directory = "netlify/functions"

# proxy /admin/* into your one `api.js` function, preserving the /admin prefix
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200
  force  = true

# same for /api/*
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
  force  = true

# everything else → your React app
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
