# netlify.toml
[build]
  # from repo root, first install your functions’ deps, then install & build the React app
  command = """
    npm install && \
    npm install --prefix rental-platform-frontend && \
    npm run build --prefix rental-platform-frontend
  """
  # where CRA will emit its production files
  publish = "rental-platform-frontend/build"

[functions]
  # point at the functions folder at the repo root
  directory = "netlify/functions"

# proxy your Express routes through the Functions endpoint
[[redirects]]
  from     = "/admin/*"
  to       = "/.netlify/functions/api/admin/:splat"
  status   = 200
  force    = true

[[redirects]]
  from     = "/api/*"
  to       = "/.netlify/functions/api/api/:splat"
  status   = 200
  force    = true

# everything else → your frontend’s client-side router
[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
