# netlify.toml
[build]
  base    = "rental-platform-frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

# proxy your Express routes through the Functions endpoint:
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
  force  = true

# everything else → client-side router
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
