# netlify.toml (at the repo root)

[build]
  base    = "rental-platform-frontend"
  publish = "build"
  command = "npm install && npm run build"

[functions]
  # relative to that same base folder
  directory = "netlify/functions"

[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
  methods = ["GET"]
