[build]
  command = "npm install && npm install --prefix rental-platform-frontend && npm run build --prefix rental-platform-frontend"
  publish = "rental-platform-frontend/build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from     = "/admin/*"
  to       = "/.netlify/functions/api/admin/:splat"
  status   = 200
  force    = true

[[redirects]]
  from     = "/api/*"
  to       = "/.netlify/functions/api/api/:splat"
  status   = 200
  force    = true

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
