# netlify.toml

[build]
  # relative to the repo root
  base    = "rental-platform-frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  # if you’re using serverless functions under rental-platform-frontend/netlify/functions
  directory = "netlify/functions"

# proxy your API routes through the Functions endpoint:
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
