[build]
  publish = "frontend/build"
  functions = "backend"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
