# netlify.toml

[build]
  base    = "rental-platform-frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  directory = "rental-platform-frontend/netlify/functions"

# Proxy API/admin calls into your Express function
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
  force  = true

# SPA fallback for all other GET requests
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
  methods = ["GET"]
