# netlify.toml

[build]
  base    = "rental-platform-frontend"       # where your React app lives
  publish = "build"                          # React’s output folder
  command = "npm install && npm run build"   # runs in rental-platform-frontend

[functions]
  directory = "netlify/functions"            # where your api.js lives (relative to repo root)

[[redirects]]
  from    = "/admin/*"
  to      = "/.netlify/functions/api/admin/:splat"
  status  = 200
  force   = true

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/api/api/:splat"
  status  = 200
  force   = true

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
