# netlify.toml

[build]
  # install root-level deps (serverless, express, etc),
  # then install & build the React app:
  command = "npm install && npm install --prefix rental-platform-frontend && npm run build --prefix rental-platform-frontend"
  publish = "rental-platform-frontend/build"

[functions]
  directory = "netlify/functions"

# proxy any /admin/* → your Lambda
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/api/admin/:splat"
  status = 200
  force  = true

# proxy any /api/* → your Lambda
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/api/:splat"
  status = 200
  force  = true

# client-side router for everything else
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
